numero = int(input('Insira o numero inteiro: '))
valor1 = 1
valor2 = 2
valor3 = 3
valor4 = 4
valor5 = 5
valor6 = 6
valor7 = 7
valor8 = 8
valor9 = 9
valor10 = 10
resultado1 = numero * valor1
resultado2 = numero * valor2
resultado3 = numero * valor3
resultado4 = numero * valor4
resultado5 = numero * valor5
resultado6 = numero * valor6
resultado7 = numero * valor7
resultado8 = numero * valor8
resultado9 = numero * valor9
resultado10 = numero * valor10

print(f'{numero} X {valor1} = {resultado1}')
print(f'{numero} X {valor2} = {resultado2}')